<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="11.2.3" />
      <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.3" />
      <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.3" />
      <PackageReference Include="Avalonia.Xaml.Behaviors" Version="11.2.0.8" />
      <PackageReference Include="Avalonia.Xaml.Interactions" Version="11.2.0.8" />
      <PackageReference Include="Avalonia.Xaml.Interactivity" Version="11.2.0.8" />
      <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.0" />
      <PackageReference Include="DynamicData" Version="9.1.1" />
      <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="1.8.0" />
      <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="9.0.1" />
      <PackageReference Include="Semi.Avalonia" Version="11.2.1.4" />
      <PackageReference Include="Semi.Avalonia.DataGrid" Version="11.2.1.4" />
    </ItemGroup>

    <ItemGroup Label="Embedded">
        <EmbeddedResource Include="BakedAssets\*.png"
                          Label="Icons"/>
        <EmbeddedResource Include="BakedAssets\Extensions\*.png"
                          Label="ExtensionsIcons"/>
    </ItemGroup>
    
    <ItemGroup>
        <AvaloniaResource Include="BakedAssets\*.ico" />
    </ItemGroup>
    
    <ItemGroup>
      <UpToDateCheckInput Remove="BakedAssets\aperture.ico" />
    </ItemGroup>
    
</Project>
